[aim]
directory = "/home/kaiz0r/.appimages/"

[tools]
editor = "kwrite"

[rpg]
level = 2
exp = 25

[memo]
text = "\\"

[aliases]
sys = "system"
app = "appman"
cdx = "codex"
q = "quests"

[test]
one = "true"
num = 5